### ISSUE TITLE
YamlLocalhostSplitFile has incorrect logger name

### ISSUE THREAD

**Issue by josephnoall** [splitio/java-client#186]
The YamlLocalhostSplitFile class is logging with a logger called _LegacyLocalhostSplitFile_, which is misleading since the LegacyLocalhostSplitFile [also uses a logger of that name](https://github.com/splitio/java-client/blob/0ddae167f06b692328f8394a68bd95dbf93a6eb8/client/src/main/java/io/split/client/LegacyLocalhostSplitFile.java#L13-L14).  This causes confusing log statements that make it look like the code went down the path to read the legacy splitFile, when it actually was on the newer code path.

See https://github.com/splitio/java-client/blob/0ddae167f06b692328f8394a68bd95dbf93a6eb8/client/src/main/java/io/split/client/YamlLocalhostSplitFile.java#L14-L16

**Comment by chillaq** [comment]
Thanks @josephnoall , I will check with the team, despite using the same logger name, the functionality is not impacted, the SDK will load the data from the YAML file.

**Comment by nmayorsplit** [comment]
Hi @josephnoall, I ckecked and was fixed in the Java SDK 4.2.0 version.

Thanks 

Nadia
