### ISSUE TITLE
Add changelog in the release notes page

### ISSUE THREAD

**Issue by natzei** [splitio/java-client#235]
Hi everyone,
any chance to include the changelogs when a new release is published? I struggle to understand if there are breaking changes between minor bumps or figure out if a patch is worth upgrading the whole codebase (we use split in a microservice architecture).

Thank you very much in advance.

**Comment by natzei** [comment]
Thank you, CHANGES.txt was exactly what I was looking for. I would suggest
to put the same information in the release page since I think it's the
first place where people look for it. Just my 2 cents.

**Comment by agustinona** [comment]
Thank you for the suggestion. I've submitted this as a request for us to incorporate into our process.

**Comment by adrian-skybaker** [comment]
I was only able to find the changelog via this ticket.

**Comment by adrian-skybaker** [comment]
I think the important thing is to have the releases visible at https://github.com/splitio/java-client/releases  .

This means we can add a watch for releases to this repository, and it's a standard location to look for historical releases and the changelog.

**Comment by nmayorsplit** [comment]
Hi @adrian-skybaker , 
We released Java SDK 4.4.6 version that contains a fix for this issue.

Thanks
Nadia

**Comment by adrian-skybaker** [comment]
Thank you. 

It would be great to one day include releases under https://github.com/splitio/java-client/releases, as Github provides an easy way to subscribe to be notified of new releases.
