### ISSUE TITLE
SDK client.destroy() does not stops all threads

### ISSUE THREAD

**Issue by shahzebkhan111** [splitio/java-client#308]
I tried to use splio.io and used an invalid API key, say testKeyXYZ, I get a timeout exception which is understandable. When I try to call `client.destroy()` in the catch block, it calls split shutdown and the services but I keep getting the following logs in the console which I don't want.

`io.split.engine.experiments.SplitFetcherImp : RefreshableSplitFetcher failed: Problem fetching splitChanges: Connection pool shut down`

I tried to call destroy() on the factory as well but logs still keep on coming. Is there anything else I am missing?

**Comment by chillaq** [comment]
Hi @shahzebkhan111 , Thanks for the info, I cannot repro this issue using latest SDK version (4.4.4), when I use incorrect API Key, I usually get the SDK timeout exception, then if I call client.destroy(), all the background threads are stopped, so no more http calls, see the debug log below:

2022-06-09 @10:22:00 INFO  (SplitFactoryImpl.java:334)     - Successful shutdown of telemetry sync task
2022-06-09 @10:22:00 DEBUG (PoolingHttpClientConnectionManager.java:232)     - Shutdown connection pool GRACEFUL
2022-06-09 @10:22:00 DEBUG (PoolingHttpClientConnectionManager.java:235)     - Connection pool shut down
2022-06-09 @10:22:00 INFO  (SplitFactoryImpl.java:336)     - Successful shutdown of httpclient

If I call client.getTreatment() method afterwards:

2022-06-09 @10:22:00 WARN  (SplitClientImpl.java:360)     - getTreatment: the SDK is not ready, results may be incorrect. Make sure to wait for SDK readiness before using this method
2022-06-09 @10:22:00 ERROR (SplitClientImpl.java:229)     - Client has already been destroyed - no calls possible

No other activity in the log.

**Comment by chillaq** [comment]
Hi @shahzebkhan111 , just checking if you have any other questions or we are good to close?

**Comment by shahzebkhan111** [comment]
> 

Thanks, @chillaq I actually tried it before but I was getting the logs even after destroying the client. Btw, I used the split with the spring boot project.

**Comment by chillaq** [comment]
Hi @shahzebkhan111 , can you enable SDK debug logging, repro the issue, then provide the full log here?

**Comment by chillaq** [comment]
Hi @shahzebkhan111 , I am following up on this issue, do you still need help?

**Comment by shahzebkhan111** [comment]
Thank you @chillaq, sorry I didn't get a chance to reproduce the issue for full logs. But let the logs get printed. Thank you.

**Comment by chillaq** [comment]
Hi @shahzebkhan111 , I am following up on this issue, do you still need help?

**Comment by chillaq** [comment]
Hi @shahzebkhan111 , I am following up on this issue, do you still need help?

**Comment by chillaq** [comment]
Hi @shahzebkhan111 ,  I am closing this thread, feel free to reopen if you still see the issue.
