### ISSUE TITLE
Split IO Initialization error

### ISSUE THREAD

**Issue by vernikachauhan1997** [splitio/java-client#349]
Hi, I am facing below error while using Split with java. I have also installed split certificate in the cacerts file of JRE/JDK, but its still showing this issue. Need your immediate help.
**Error: [SPLIT-Initialization-0] ERROR io.split.engine.experiments.SplitFetcherImp - RefreshableSplitFetcher failed: Problem fetching splitChanges: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target**

**Comment by agustinona** [comment]
@vernikachauhan1997 I'm following up on this. Were you able to follow the troubleshooting steps in the article I sent? If the problem persists, could you provide the Split SDK version you are running as well as your JRE version?

**Comment by vernikachauhan1997** [comment]
Hi ,

I tried the troubleshooting steps, but still same issue
Split SDK version:4.5.0
Java version: 1.8.0_341 jdk

Regards,
Vernika Chauhan

**Comment by agustinona** [comment]
@vernikachauhan1997 I would like to move this into a support ticket for better tracking. You should receive an email from support@split.io. Please let me know if you didn't.

**Comment by agustinona** [comment]
Closing this issue since it has been resolved through our internal ticketing system
