### ISSUE TITLE
Logs are not being generated correctly

### ISSUE THREAD

**Issue by ClaudenirFreitas** [splitio/java-client#364]
Hi all,

Java Client is generating some logs without details e.g.

Example 1: [Pipeline](https://github.com/splitio/java-client/actions/runs/3704635709/jobs/6277492092#step:6:947)
```
 WARN [main] (SplitClientImpl.java:252) - %s: you passed "foo" that does not exist in this environment, please double check what Splits exist in the web console.
```

Example 2: [Pipeline](https://github.com/splitio/java-client/actions/runs/3704635709/jobs/6277492092#step:6:1136)
```
ERROR [main] (SplitClientImpl.java:303) - %s: split_names must be a non-empty array
```

As you can see, there is a `%s`.

**Comment by ClaudenirFreitas** [comment]
[This MR](https://github.com/splitio/java-client/pull/365) will fix this incident.

**Comment by hbqdev** [comment]
Hi @ClaudenirFreitas 
We see that you have submitted a PR for this, thank you

**Comment by ClaudenirFreitas** [comment]
No problem @hbqdev .

**Comment by nmayorsplit** [comment]
Hi @ClaudenirFreitas,
I'm going to close it because the 4.7.0 version fixed it.

Thank you
