### ISSUE TITLE
SplitCacheConsumer.get returns a different treatment default value on 4.7.1 than 4.7.0

### ISSUE THREAD

**Issue by Jon-Mallozzi** [splitio/java-client#392]
Hi, I am working on upgrading to 4.7.1, but one of my unit tests in my build pipeline keeps failing due to the default value being returned for the treatment is different than expected. 

In our unit tests, we load mock treatments in yaml in this format:
```
- Treatment1:
    treatment: "on"
    keys: ["key1", "key2"]
```

Our failing unit test calls a function that gets the treatment value using this logic:
```
splitClient.getTreatment(key, featureName);
```
where key is key3 and featureName is Treatment1.

Digging into the java-client source for `getTreatment` with a debugger, I found that the treatment result is gotten from this line of code:

[EvaluatorImp.TreatmentLabelAndChangeNumber result = this._evaluator.evaluateFeature(matchingKey, bucketingKey, split, attributes);](https://github.com/splitio/java-client/blob/master/client/src/main/java/io/split/client/SplitClientImpl.java#L307)

Which calls [EvaluateFeature](https://github.com/splitio/java-client/blob/master/client/src/main/java/io/split/engine/evaluator/EvaluatorImp.java#L33) to get the cache value from SplitCacheConsumer and then uses that to get the treatment value.

When getting the treatment value, it realizes that key3 is not in the ParsedCondition `if key is in segment ["key1","key3"] then split 100:on,0:null` and returns the default value here: https://github.com/splitio/java-client/blob/master/client/src/main/java/io/split/engine/evaluator/EvaluatorImp.java#L104

The issue is that in version 4.7.0 the defaultTreatment gotten from `SplitCacheConsumer` is control while the defaultTreatment on 4.7.1 is "on". 

4.7.0: 
<img width="617" alt="Screen Shot 2023-05-01 at 4 28 43 PM" src="https://user-images.githubusercontent.com/104797527/235525403-a68e81f6-46b6-4285-bb1f-73f2efb62b52.png">

4.7.1:
<img width="634" alt="Screen Shot 2023-05-01 at 4 21 29 PM" src="https://user-images.githubusercontent.com/104797527/235525459-3486c02e-afc9-458b-9f20-f8a36d5cb490.png">

Currently, our codebase assumes when the key is not in the set of keys for a Treatment, then the flag is considered off. Do we need to update our code/treatment config to reflect this for the new update, or is this a bug?

**Comment by hbqdev** [comment]
hi @Jon-Mallozzi 
Can you please clarify more for us the testing scenario?

Are you testing in localhost mode with the YAML file?

Do you have any SDK logs for both versions that you can reproduce this issue and share with us?

Have you tried evaluating directly against Split.io? Do you get back the expected treatment?

Regards,

**Comment by Jon-Mallozzi** [comment]
Hi @hbqdev,

> Can you please clarify more for us the testing scenario? Are you testing in localhost mode with the YAML file?

Our unit tests load the YAML file in an ApplicationContextRunner with localhost mode. Though I noticed in 4.7.1 the _trafficeTypeName became user instead of localhost

```
ApplicationContextRunner contextRunner =
      new ApplicationContextRunner()
          .withPropertyValues("splitio.configPath:classpath:splitio.yaml")
          .withUserConfiguration(SplitConfiguration.class);

SplitFactoryBuilder.build(LOCALHOST, getOfflineConfig()).client();
```

> Do you have any SDK logs for both versions that you can reproduce this issue and share with us?
I am not familiar with how to get these logs.

> Have you tried evaluating directly against Split.io? Do you get back the expected treatment?
Currently, it's working as expected with 4.7.0. Due to the failing unit, we have not been able to push 4.7.1 to an environment that evaluates directly against Split.io. I can try getting credentials to test this, but currently, they are locked by permissions I don't have.

**Comment by Jon-Mallozzi** [comment]
Ok with debug mode on, this is what the unit test logged in 4.7.0:

```
13:35:04.024 [main] INFO  com.xxxxx.xxxxx.featureflag.SplitConfiguration - SplitClient in local mode. Resource file: class path resource [splitio.yaml]
13:35:04.024 [main] WARN  com.cxxxxx.xxxxx..featureflag.SplitConfiguration - Split.io API token not provided. Using localhost treatment data from: /Users/jonathanmallozzi/projects/xxxxx/xxxxx/target/test-classes/splitio.yaml
13:35:04.025 [main] INFO  io.split.client.LocalhostSplitFactory - Starting Split in localhost mode with file at /Users/jonathanmallozzi/projects/xxxxx/xxxxx/target/test-classes/splitio.yaml
13:35:04.028 [main] WARN  com.xxxxx.xxxxx.featureflag.SplitConfiguration - Split.io API token not provided. Using localhost treatment data from: /Users/jonathanmallozzi/projects/xxxxx/xxxxx/target/test-classes/splitio.yaml
13:35:04.029 [main] INFO  io.split.client.LocalhostSplitFactory - Starting Split in localhost mode with file at /Users/jonathanmallozzi/projects/xxxxx/xxxxx/target/test-classes/splitio.yaml
13:35:04.033 [main] INFO  com.xxxxx.xxxx.featureflag.SplitConfiguration - Starting up Split.IO client
```

and this is 4.7.1:
```
13:32:06.292 [main] INFO  com.xxxxx.xxxxx.featureflag.SplitConfiguration - SplitClient in local mode. Resource file: class path resource [splitio.yaml]
13:32:06.292 [main] WARN  com.xxxxx.xxxxx.featureflag.SplitConfiguration - Split.io API token not provided. Using localhost treatment data from: /Users/jonathanmallozzi/projects/xxxxx/xxxxx/target/test-classes/splitio.yaml
13:32:06.292 [main] WARN  io.split.client.ApiKeyCounter - factory instantiation: You already have 3 factories with this API Key. We recommend keeping only one instance of the factory at all times (Singleton pattern) and reusing it throughout your application.
13:32:06.295 [main] INFO  io.split.engine.common.LocalhostSynchronizer - Refresh enable is false. The synchronization tasks are not going to start
13:32:06.295 [main] WARN  com.xxxxx.xxxxx.featureflag.SplitConfiguration - Split.io API token not provided. Using localhost treatment data from: /Users/jonathanmallozzi/projects/xxxxx/xxxxx/target/test-classes/splitio.yaml
13:32:06.296 [main] WARN  io.split.client.ApiKeyCounter - factory instantiation: You already have 4 factories with this API Key. We recommend keeping only one instance of the factory at all times (Singleton pattern) and reusing it throughout your application.
13:32:06.298 [main] INFO  io.split.engine.common.LocalhostSynchronizer - Refresh enable is false. The synchronization tasks are not going to start
13:32:06.299 [main] INFO  com.xxxxx.xxxxx.featureflag.SplitConfiguration - Starting up Split.IO client
13:32:06.301 [main] INFO  io.split.client.SplitFactory - Shutdown called for split
13:32:06.301 [main] INFO  io.split.client.SplitFactory - Successful shutdown of syncManager
```

**Comment by hbqdev** [comment]
Hi @Jon-Mallozzi 
Thank you for the information, we are still reviewing the behavior of the SDK.

For now, you can try the workaround for the reporter to just set the default treatment for the feature flag in the yaml to explicitly state what treatment you want to be returned for keys that are not individually targeted. E.g:

- Treatment1:
    treatment: "on"
    keys: ["key1", "key2"]
- Treatment1:
    treatment: "off"

That should be able to pass the unit test.

Regards,

**Comment by hbqdev** [comment]
Hi @Jon-Mallozzi 
The issue has now been fixed.

Regards
