### ISSUE TITLE
SplitIO not letting SpringBootApplication end process

### ISSUE THREAD

**Issue by jcolaco-nmz** [splitio/java-client#41]
When using localhost as Split IO key and there's no file, split creates a non daemon thread that continuously tries to poll the file, not letting the application to end.
 
I'm using version 2.2.0

**Comment by patricioe** [comment]
Thanks for flagging this. We'll address shortly.

**Comment by patricioe** [comment]
@jcolaco-nmz https://github.com/splitio/java-client/pull/42 contains the fix. Feel free to try it in the meantime. We'll be publishing a point release soon.

**Comment by patricioe** [comment]
@jcolaco-nmz Feel free to try out 2.2.2 version. We haven't update the official docs yet as we are waiting for our internal quality procedures to clear but you should be good to try it out.

**Comment by jcolaco-nmz** [comment]
@patricioe It's fixed. Thank you for your quick response.
