### ISSUE TITLE
Connection timeout issue in io.split.client:java-client:4.2.1

### ISSUE THREAD

**Issue by sheetalj2205** [splitio/java-client#472]
We're using the 4.2.1 version of split.io and we have received network connectivity issues which are related to SDK. I am adding logs here for the reference:

`RefreshableSplitFetcher failed: Problem fetching splitChanges: Connect to []() [] failed: connect timed out`

`Unrecoverable error in streaming subsystem. SDK will work in polling-mode and will not retry an SSE connection.`

**Comment by agustinona** [comment]
Marking this as resolved as it was addressed through support.
