### ISSUE TITLE
java.lang.NoSuchMethodError: 'void redis.clients.jedis.JedisPoolConfig.setMinEvictableIdleTime(java.time.Duration)'

### ISSUE THREAD

**Issue by moshiul-rabbi-seera** [splitio/java-client#509]
public class JedisPoolConfig extends GenericObjectPoolConfig<Jedis> {
    public JedisPoolConfig() {
        this.setTestWhileIdle(true);
        this.setMinEvictableIdleTime(Duration.ofMillis(60000L));
        this.setTimeBetweenEvictionRuns(Duration.ofMillis(30000L));
        this.setNumTestsPerEvictionRun(-1);
    }
}

![Screen Shot 2024-06-27 at 5 58 48 PM](https://github.com/splitio/java-client/assets/125877056/b7dcfe53-eb59-4b7f-8b10-841fc7e7e264)

**Comment by chillaq** [comment]
Hi @moshiul-rabbi-seera, thanks for the info, checking this issue now.

Thanks
Bilal

**Comment by chillaq** [comment]
Hi @moshiul-rabbi-seera, The "setMinEvictableIdleTime" exist in class BaseObjectPoolConfig<T>, which is extended in GenericObjectPoolConfig<T>, see screenshots.

![Untitled2](https://github.com/splitio/java-client/assets/41021307/3b3569a9-8634-4679-a5ab-d2bcae30a0c8)
![Untitled](https://github.com/splitio/java-client/assets/41021307/eaea0009-7d5b-445d-b9c7-29900bf014a1)

**Comment by moshiul-rabbi-seera** [comment]
Many thanks @chillaq. Its due to commons-pool2 library version.
