### ISSUE TITLE
Getting Timeout exception in client.blockUntilReady method

### ISSUE THREAD

**Issue by AdityaSingh04SAP** [splitio/java-client#514]
Getting this exception:-
Caused by: java.util.concurrent.TimeoutException: SDK was not ready in 10000 milliseconds
	at io.split.client.SplitClientImpl.blockUntilReady(SplitClientImpl.java:268)

Using apikey: localhost

We are passing a yaml file. So, when we are calling the client.blockUntilReady() method, we are getting a TimeOutException there.

This was working perfectly till version 4.7.0. But upon upgrading it to 4.7.1, it started to fail. So, can you please have this checked.

yaml that is being used:-
```
- PL-99999:
 treatment: "on"
```

Feel free to reach out to me if anything else is required from my end

**Comment by agustinona** [comment]
Hi @AdityaSingh04SAP 
Your yaml file appears to be incorrectly indented. Could you try this one instead with 4-space indentation?
```
- PL-99999:
    treatment: "on"
```
Note that your file wouldn't have worked in version 4.7.0 either, but the behavior was slightly changed in 4.7.1 after updating our YAML parser. In 4.7.0 a failed parsing resulted in the `blockUntilReady` method immediately returning (no TimeoutException), but you'd have received control treatments when evaluating your features. Starting from 4.7.1, a failure parsing the yaml file results in an initialization failure and subsequent timeout exception.

**Comment by agustinona** [comment]
@AdityaSingh04SAP you are welcome!
I'm not sure what changes to our documentation are you suggesting we make?

**Comment by AdityaSingh04SAP** [comment]
@agustinona I was referring to the indentation thing. That the yaml needs to have more than 2 spaces.

**Comment by agustinona** [comment]
@AdityaSingh04SAP the YAML file in the docs contains 4-space indentations currently.
