### ISSUE TITLE
Support redis integration for split synchronizer

### ISSUE THREAD

**Issue by brendangibat** [splitio/java-client#69]
Java SDK docs state: ```Java SDK can connect to the Split Synchronizer only in Proxy mode, as of now it does not support the Redis integration.```

We're currently using redis synchronizer for other language sdk's - it would be helpful to avoid standing up proxy mode synchronizer.

**Comment by goldensun8891** [comment]
Hi Brendan,

Thanks for the feedback! Our team is also chatting about this request with your teammate Matt via email so I'm going to close out this for now and let the communication go through the emails!
